/* Invoices are snapshots; payments are manually recorded, not processed. */
'use strict';
const BillingUI = {
  list() {
    const db=App.db;const total=db.billing.reduce((s,i)=>s+i.total,0),paid=db.payments.reduce((s,p)=>s+p.amount,0);
    UI.content.innerHTML=UI.heading('ACCOUNTS & COLLECTIONS','Billing & payments','Create itemized invoices and keep an accurate payment record.',UI.button(icon('plus')+' Create invoice','invoice-create','','primary'))+
      `<div class="stat-grid">${UI.stat('Total invoiced',formatCurrency(total),db.billing.length+' invoices')}${UI.stat('Collected',formatCurrency(paid),'Recorded payments','success')}${UI.stat('Outstanding',formatCurrency(total-paid),'Remaining to collect','danger')}</div><section class="card"><div class="card-body">${App.searchbar('Search invoice, ticket, or customer…',['Pending','Partial','Paid'])}<div class="list-tools"><span class="muted">One invoice per repair ticket</span>${UI.button('Export CSV','invoice-export')}</div></div><div id="invoiceRows"></div></section>`;
    App.wireSearch(()=>{const rows=db.billing.filter(i=>App.matches([i.id,i.ticket_id,i.customer?.name||App.customer(i.customer_id)])&&(!App.filter||Repo.invoiceBalance(i,db).status===App.filter));this.filtered=rows;document.getElementById('resultCount').textContent=rows.length+' invoices';document.getElementById('invoiceRows').innerHTML=UI.table(['Invoice / date','Customer / ticket','Total','Balance','Status','Actions'],rows.slice().reverse().map(i=>{const b=Repo.invoiceBalance(i,db);return `<tr><td><b>${E(i.id)}</b><span class="cell-sub">${E(formatDate(i.createdAt))}</span></td><td>${E(i.customer?.name||App.customer(i.customer_id))}<span class="cell-sub">${E(i.ticket_id)}</span></td><td>${formatCurrency(i.total)}</td><td>${formatCurrency(b.balance)}</td><td>${pill(b.status)}</td><td><div class="table-actions">${UI.button('View / print','invoice-view',i.id)}${b.balance>0?UI.button('Record payment','payment-add',i.id,'primary'):''}${!b.paid?UI.button('Delete','invoice-delete',i.id,'danger'):''}</div></td></tr>`;}),'No matching invoices. Create an invoice from a repair ticket.');});
  },
  create(selected='') {
    const db=Storage.database(),tickets=db.tickets.filter(t=>!['Delivered','Cancelled'].includes(t.status)&&!db.billing.some(i=>i.ticket_id===t.id));
    if(!tickets.length)throw new Error('No uninvoiced open tickets are available. Create a repair ticket first.');
    const body=`<div class="form-grid">${UI.select('Repair ticket','ticket_id',tickets.map(t=>[t.id,t.id+' · '+t.model]),selected||tickets[0].id)}${UI.field('Labor / service charge (₹)','labor',0,'number','min="0" step="0.01" required')}${UI.field('Tax rate (%)','tax_rate',0,'number','min="0" max="100" step="0.01" required')}${UI.field('Discount (₹)','discount',0,'number','min="0" step="0.01" required')}${UI.area('Invoice notes','notes','','maxlength="1000"')}</div><div class="invoice-preview" id="invoicePreview"></div><p class="muted small-note">Used parts are included automatically. Issuing this invoice locks its parts and customer snapshot.</p>`;
    UI.modal('Create invoice',body,{wide:true,submit:'Create invoice',onSubmit:async p=>{await Repo.createInvoice(p);toast('Invoice created.');await App.render();},after:overlay=>{
      const form=overlay.querySelector('form');const update=()=>{const p=Object.fromEntries(new FormData(form));const t=tickets.find(x=>x.id===p.ticket_id);try{const totals=Repo.invoicePreview(t,p.labor,p.tax_rate,p.discount);overlay.querySelector('#invoicePreview').innerHTML=`<div><span>Parts</span><b>${formatCurrency(totals.parts_total)}</b></div><div><span>Labor</span><b>${formatCurrency(totals.labor)}</b></div><div><span>Discount</span><b>− ${formatCurrency(totals.discount)}</b></div><div><span>Tax</span><b>${formatCurrency(totals.tax_amount)}</b></div><div class="preview-total"><span>Total</span><b>${formatCurrency(totals.total)}</b></div>`;}catch(e){overlay.querySelector('#invoicePreview').textContent=e.message;}};form.addEventListener('input',update);form.addEventListener('change',update);update();
    }});
  },
  invoiceHTML(inv,db) {
    const b=Repo.invoiceBalance(inv,db),customer=inv.customer||db.customers.find(c=>c.id===inv.customer_id)||{},settings=inv.business||db.payment_settings;
    return `<article class="invoice-sheet"><div class="invoice-head"><div class="brand-block"><b>${E(settings.business_name||'Rep-Flow Repair Services')}</b><div class="tagline">Repair services · Invoice</div><p class="small-note">${E(settings.address||'')}<br>${E(settings.phone||'')}</p></div><div class="invoice-meta"><strong>${E(inv.id)}</strong><br>${E(formatDate(inv.createdAt))}<br>${pill(b.status)}</div></div><div class="detail-grid"><div><span>Billed to</span><b>${E(customer.name)}</b><p>${E(customer.phone)}<br>${E(customer.email||'')}<br>${E(customer.address||'')}</p></div><div><span>Repair reference</span><b>${E(inv.ticket_id)}</b><p>${E(inv.device)}</p></div></div><table class="invoice-table"><thead><tr><th>Description</th><th>Qty</th><th>Rate</th><th>Amount</th></tr></thead><tbody>${(inv.lines||[]).map(l=>`<tr><td>${E(l.name)}</td><td>${l.quantity}</td><td>${formatCurrency(l.unit_price)}</td><td>${formatCurrency(l.quantity*l.unit_price)}</td></tr>`).join('')}${inv.labor>0?`<tr><td>Labor / service charge</td><td>1</td><td>${formatCurrency(inv.labor)}</td><td>${formatCurrency(inv.labor)}</td></tr>`:''}</tbody></table><div class="invoice-totals"><div><span>Subtotal</span><span>${formatCurrency(inv.subtotal)}</span></div><div><span>Discount</span><span>− ${formatCurrency(inv.discount)}</span></div><div><span>Tax (${inv.tax_rate}%)</span><span>${formatCurrency(inv.tax_amount)}</span></div><div class="grand"><span>Total</span><span>${formatCurrency(inv.total)}</span></div><div><span>Paid</span><span>${formatCurrency(b.paid)}</span></div><div class="grand"><span>Balance due</span><span>${formatCurrency(b.balance)}</span></div></div>${inv.notes?`<p class="preline small-note">${E(inv.notes)}</p>`:''}<div class="invoice-payment-details">${settings.upi_qr_photo_id&&db.photo_data?.[settings.upi_qr_photo_id]?`<img class="invoice-qr" src="${E(db.photo_data[settings.upi_qr_photo_id])}" alt="Payment QR image">`:""}${settings.upi_id?`<p><b>UPI:</b> ${E(settings.upi_id)}</p>`:''}${settings.bank_name?`<p><b>Bank:</b> ${E(settings.bank_name)} · ${E(settings.account_holder)}<br>Account: ${E(settings.account_number)} · IFSC: ${E(settings.ifsc)}</p>`:''}${settings.instructions?`<p class="muted">${E(settings.instructions)}</p>`:''}</div><p class="invoice-thanks">Thank you for choosing ${E(settings.business_name||'Rep-Flow')}.</p></article>`;
  },
  async view(id) {
    const db=Storage.database(),inv=findRecord(db,'billing',id),b=Repo.invoiceBalance(inv,db),payments=db.payments.filter(p=>p.invoice_id===id);
    UI.modal('Invoice · '+id,`<div class="quick-actions no-print">${UI.button('Print / Save PDF','invoice-print',id,'primary')}${b.balance>0?UI.button('Record payment','payment-add',id):''}</div>${this.invoiceHTML(inv,db)}<h4>Recorded payments</h4>${UI.table(['Date','Method','Reference','Amount'],payments.map(p=>`<tr><td>${E(formatDateTime(p.createdAt))}</td><td>${E(p.method)}</td><td>${E(p.reference||'—')}</td><td>${formatCurrency(p.amount)}</td></tr>`),'No payments recorded.')}`,{wide:true});
  },
  payment(id) {
    const db=Storage.database(),inv=findRecord(db,'billing',id),b=Repo.invoiceBalance(inv,db);
    if(b.balance<=0)throw new Error('This invoice is already fully paid.');
    UI.modal('Record payment · '+id,`<div class="info-note">Outstanding balance: <b>${formatCurrency(b.balance)}</b></div><div class="form-grid">${UI.field('Amount received (₹)','amount',b.balance,'number',`min="0.01" max="${b.balance}" step="0.01" required`)}${UI.select('Payment method','method',['Cash','UPI','Bank transfer','Card'])}${UI.field('UTR / transaction reference','reference','','text','maxlength="100"')}${UI.area('Payment note','note','','maxlength="500"')}</div><p class="muted">Record only payments you have independently confirmed. This form does not transfer money.</p>`,{submit:'Record payment',onSubmit:async p=>{await Repo.recordPayment(id,p);toast('Payment recorded.');await App.render();},after:overlay=>{const method=overlay.querySelector('[name=method]'),ref=overlay.querySelector('[name=reference]');method.onchange=()=>{ref.required=method.value!=='Cash';};}});
  },
  async settings() {
    const s=App.db.payment_settings;
    UI.content.innerHTML=UI.heading('BUSINESS PREFERENCES','Payment settings','Set the business details used on new invoices and show your payment instructions.')+
      `<div class="two-col"><section class="card"><div class="card-header"><h3>Business & payment details</h3></div><div class="card-body"><form id="settingsForm"><div class="form-grid">${UI.field('Business name','business_name',s.business_name,'text','required')}${UI.field('Business phone','phone',s.phone,'tel')}${UI.field('Business address','address',s.address)}${UI.field('UPI ID','upi_id',s.upi_id,'text','placeholder="yourname@bank"')}${UI.field('Bank name','bank_name',s.bank_name)}${UI.field('Account holder','account_holder',s.account_holder)}${UI.field('Account number','account_number',s.account_number,'text','inputmode="numeric"')}${UI.field('IFSC','ifsc',s.ifsc)}${UI.field('Branch','branch',s.branch)}${UI.area('Payment instructions','instructions',s.instructions)}</div><div class="form-error" id="settingsError" role="alert" hidden></div><div class="form-actions"><button type="submit" class="btn btn-primary">Save settings</button></div></form></div></section><section class="card qr-card"><div class="card-header"><h3>Payment QR image</h3></div><div class="card-body"><div class="qr-preview" id="qrPreview">No QR image uploaded</div><p class="muted small-note">Upload your own payment QR image. Verify that it scans correctly after compression.</p><div class="quick-actions">${UI.button('Upload QR image','qr-upload')}${s.upi_qr_photo_id?UI.button('Remove','qr-remove','','danger'):''}</div><div class="info-note">Existing invoices retain the business details saved when they were created. New settings apply to future invoices.</div></div></section></div>`;
    document.getElementById('settingsForm').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('[type=submit]');button.disabled=true;const error=document.getElementById('settingsError');error.hidden=true;try{await Repo.saveSettings(Object.fromEntries(new FormData(e.target)));toast('Payment settings saved.');App.db=Storage.database();}catch(err){error.textContent=err.message;error.hidden=false;}finally{button.disabled=false;}};
    if(s.upi_qr_photo_id){const src=await PhotoStore.get(s.upi_qr_photo_id);if(src)document.getElementById('qrPreview').innerHTML=`<img src="${E(src)}" alt="Business payment QR code">`;}
  },
  async action(action,id) {
    if(action==='invoice-create')return this.create();
    if(action==='invoice-view')return this.view(id);
    if(action==='invoice-delete')return UI.confirm('Delete this unpaid invoice? Its repair will become available for invoicing again.',()=>Repo.deleteInvoice(id));
    if(action==='payment-add')return this.payment(id);
    if(action==='invoice-print'){
      const db=Storage.database(),inv=findRecord(db,'billing',id);document.getElementById('printArea')?.remove();const area=document.createElement('div');area.id='printArea';area.innerHTML=this.invoiceHTML(inv,db);document.body.append(area);window.addEventListener('afterprint',()=>area.remove(),{once:true});window.print();return;
    }
    if(action==='invoice-export')return UI.csv('repflow-invoices.csv',['Invoice','Ticket','Customer','Date','Total','Paid','Balance','Status'],(this.filtered||[]).map(i=>{const b=Repo.invoiceBalance(i);return[i.id,i.ticket_id,i.customer?.name,i.createdAt,i.total,b.paid,b.balance,b.status];}));
    if(action==='qr-upload')return UI.modal('Upload a payment QR image',UI.field('QR image','qr','','file','accept="image/jpeg,image/png,image/webp" required'),{submit:'Save QR image',onSubmit:async(p,form)=>{await Repo.saveQR(form.elements.qr.files[0]);toast('QR image saved.');await App.render();}});
    if(action==='qr-remove')return UI.confirm('Remove the saved payment QR image?',()=>Repo.removeQR());
  }
};
