/* Repair intake, workboard, timeline, parts, photos and handover. */
'use strict';
const TicketUI = {
  viewMode:'table',
  list() {
    if(!App.filter)App.filter=new URLSearchParams(location.search).get('status')||'';
    const manager=App.user.role!=='technician';
    UI.content.innerHTML=UI.heading('SERVICE OPERATIONS',manager?'Repair tickets':'My repair tickets','Track devices from intake through diagnosis, repair, and delivery.',manager?UI.button(icon('plus')+' New repair','ticket-new','','primary'):'')+
      `<section class="card"><div class="card-body">${App.searchbar('Search ticket, device, or customer…',TICKET_STATUSES)}<div class="list-tools"><div class="segmented"><button type="button" id="tableView" class="${this.viewMode==='table'?'active':''}">Table</button><button type="button" id="boardView" class="${this.viewMode==='board'?'active':''}">Board</button></div><button class="btn btn-outline btn-sm" data-action="ticket-export">Export CSV</button></div></div><div id="ticketRows"></div></section>`;
    const draw=()=>{const rows=Repo.visibleTickets(App.db).filter(t=>App.matches([t.id,t.model,App.customer(t.customer_id),t.serial_number||''])&&(!App.filter||t.status===App.filter));this.filtered=rows;document.getElementById('resultCount').textContent=rows.length+' tickets';
      document.getElementById('ticketRows').innerHTML=this.viewMode==='table'?App.ticketTable(rows.slice().reverse()):`<div class="workboard card-body">${TICKET_STATUSES.filter(s=>!App.filter||s===App.filter).map(s=>`<div class="workboard-col"><h4>${E(s)} <span class="count">${rows.filter(t=>t.status===s).length}</span></h4>${rows.filter(t=>t.status===s).map(t=>`<button class="workboard-card" data-action="ticket-view" data-id="${E(t.id)}"><div class="wc-ticket">${E(t.id)} ${pill(t.priority)}</div><div class="wc-device">${E(t.model)}</div><div class="wc-device">${E(App.customer(t.customer_id))}</div><div class="wc-due">Due ${E(formatDate(t.due_date))}</div></button>`).join('')||'<div class="workboard-empty">No tickets</div>'}</div>`).join('')}</div>`;
    };
    App.wireSearch(draw);document.getElementById('tableView').onclick=()=>{this.viewMode='table';this.list();};document.getElementById('boardView').onclick=()=>{this.viewMode='board';this.list();};
  },
  edit(id='') {
    const db=Storage.database(),t=id?ticketAccess(db,id):{};if(!db.customers.length){UI.modal('Add a customer first','<p>Create a customer record before checking in a device.</p><a class="btn btn-primary" href="customers.html">Open customers</a>');return;}
    const body=`<div class="form-grid">${UI.select('Customer','customer_id',db.customers.map(c=>[c.id,c.name+' · '+c.phone]),t.customer_id||db.customers[0].id,'required')}${UI.select('Device type','device_type',['Laptop','Desktop','Mobile','Tablet','Printer','Other'],t.device_type||'Laptop')}${UI.field('Device / model','model',t.model,'text','required maxlength="150"')}${UI.field('Serial number','serial_number',t.serial_number,'text','maxlength="100"')}${UI.select('Priority','priority',['Low','Normal','High','Urgent'],t.priority||'Normal')}${UI.select('Assigned technician','technician_id',[['','Unassigned'],...db.technicians.filter(x=>x.status==='Active').map(x=>[x.id,x.name])],t.technician_id||'')}${UI.field('Due date','due_date',t.due_date,'date')}${UI.field('Estimated cost (₹)','estimate',t.estimate||0,'number','min="0" step="0.01"')}${UI.area('Problem description','issue',t.issue,'required maxlength="2000"')}${UI.area('Accessories / intake condition','accessories',t.accessories,'maxlength="300"')}</div>`;
    UI.modal(id?'Edit repair · '+id:'Check in a repair',body,{submit:id?'Save changes':'Create ticket',wide:true,onSubmit:async p=>{await Repo.saveTicket(id,p);toast(id?'Repair updated.':'Repair ticket created.');await App.render();}});
  },
  async detail(id) {
    const db=Storage.database(),t=ticketAccess(db,id),customer=findRecord(db,'customers',t.customer_id),tech=db.technicians.find(x=>x.id===t.technician_id);const manager=Auth.hasRole(MANAGERS);const open=!['Delivered','Cancelled'].includes(t.status);const invoice=db.billing.find(i=>i.ticket_id===id);
    const tabs=['Overview','Notes','Parts','Photos','Timeline'];
    const body=`<div class="ticket-summary"><div><div class="eyebrow">${E(t.device_type)} · ${E(t.serial_number||'No serial number')}</div><h2>${E(t.model)}</h2><span>${E(customer.name)} · ${E(customer.phone)}</span></div><div>${pill(t.status)} ${pill(t.priority)}</div></div><div class="quick-actions detail-actions">${open&&manager?UI.button('Edit intake','ticket-edit',id):''}${open&&(NEXT_STATUS[t.status]||[]).length?UI.button('Update status','ticket-status',id,'primary'):''}${manager&&!invoice&&open?`<a class="btn btn-outline" href="billing.html?ticket=${encodeURIComponent(id)}">Create invoice</a>`:''}${invoice&&manager?`<a class="btn btn-outline" href="billing.html?q=${encodeURIComponent(invoice.id)}">${E(invoice.id)}</a>`:''}</div>
      <div class="tab-bar" role="tablist" aria-label="Ticket sections">${tabs.map((tab,i)=>`<button class="tab-btn ${i===0?'active':''}" type="button" role="tab" aria-selected="${i===0}" data-tab="${tab}" aria-controls="tab-${tab}">${tab}${tab==='Notes'?` (${(t.notes||[]).length})`:tab==='Photos'?` (${(t.photos||[]).length})`:''}</button>`).join('')}</div>
      <section class="tab-panel active" id="tab-Overview" role="tabpanel"><div class="detail-grid"><div><span>Customer</span><b>${E(customer.name)}</b></div><div><span>Technician</span><b>${E(tech?.name||'Unassigned')}</b></div><div><span>Created</span><b>${E(formatDate(t.createdAt))}</b></div><div><span>Due date</span><b>${E(formatDate(t.due_date))}</b></div><div><span>Estimated cost</span><b>${formatCurrency(t.estimate)}</b></div><div><span>Current invoice</span><b>${invoice?E(invoice.id)+' · '+Repo.invoiceBalance(invoice,db).status:'Not yet invoiced'}</b></div></div><h4>Problem reported</h4><p class="preline detail-text">${E(t.issue)}</p><h4>Accessories / intake condition</h4><p class="preline detail-text">${E(t.accessories||'No accessories recorded.')}</p>${t.status==='Delivered'?'<div class="info-note">Device tested · Accessories returned · Customer received the device</div>':''}</section>
      <section class="tab-panel" id="tab-Notes" role="tabpanel">${open?UI.button(icon('plus')+' Add repair note','ticket-note',id):''}<div class="notes-list">${(t.notes||[]).slice().reverse().map(n=>`<article class="note-card"><p class="preline">${E(n.text)}</p><span class="muted">${E(n.by)} · ${E(formatDateTime(n.at))}</span></article>`).join('')||'<div class="empty-state">No repair notes yet.</div>'}</div></section>
      <section class="tab-panel" id="tab-Parts" role="tabpanel">${open&&!invoice?UI.button(icon('plus')+' Use inventory part','ticket-usepart',id):''}${invoice?'<p class="info-note">Parts are locked because this repair has an invoice.</p>':''}${UI.table(['Part','Quantity','Unit price','Total',''],(t.parts||[]).map(p=>`<tr><td>${E(p.name)}<span class="cell-sub">${E(p.sku)}</span></td><td>${p.quantity}</td><td>${formatCurrency(p.unit_price)}</td><td>${formatCurrency(p.quantity*p.unit_price)}</td><td>${open&&!invoice?`<button type="button" class="btn btn-danger btn-sm" data-action="ticket-returnpart" data-id="${E(id)}" data-part="${E(p.part_id)}">Return</button>`:''}</td></tr>`),'No parts used on this repair.')}<p class="muted small-note">Using a part reduces available stock immediately. Returning it restores stock.</p></section>
      <section class="tab-panel" id="tab-Photos" role="tabpanel">${open?UI.button(icon('plus')+' Add repair photo','ticket-photo',id):''}<p class="muted small-note">Images are compressed and saved in localStorage. Export a backup before clearing browser data.</p><div class="photo-grid">${(t.photos||[]).map(p=>`<div class="photo-tile"><button class="photo-thumb" type="button" data-action="ticket-photo-view" data-id="${E(id)}" data-photo="${E(p.id)}"><img data-photo-id="${E(p.id)}" alt="${E(p.caption||p.kind+' repair photo')}"><span class="photo-caption">${E(p.kind)} · ${E(p.caption)}</span></button>${open?`<button type="button" class="btn btn-danger btn-sm" data-action="ticket-photo-delete" data-id="${E(id)}" data-photo="${E(p.id)}">Remove</button>`:''}</div>`).join('')||'<div class="empty-state">No repair photos yet.</div>'}</div></section>
      <section class="tab-panel" id="tab-Timeline" role="tabpanel"><ul class="timeline">${(t.history||[]).slice().reverse().map(h=>`<li><div class="dot"></div><div class="tcontent"><b>${E(h.status)}</b><div class="tmeta">${E(h.by)} · ${E(formatDateTime(h.at))}</div><div class="tnote">${E(h.note)}</div></div></li>`).join('')}</ul></section>`;
    const overlay=UI.modal(id+' · Repair details',body,{wide:true});
    overlay.querySelectorAll('[data-tab]').forEach(btn=>btn.onclick=()=>{overlay.querySelectorAll('[data-tab]').forEach(b=>{b.classList.toggle('active',b===btn);b.setAttribute('aria-selected',b===btn);});overlay.querySelectorAll('.tab-panel').forEach(p=>p.classList.toggle('active',p.id==='tab-'+btn.dataset.tab));});
    for(const img of overlay.querySelectorAll('[data-photo-id]')){const src=await PhotoStore.get(img.dataset.photoId);if(src)img.src=src;else img.alt='Photo unavailable in this browser';}
  },
  status(id) {
    const t=ticketAccess(Storage.database(),id);const next=(NEXT_STATUS[t.status]||[]).filter(s=>Auth.hasRole(MANAGERS)||!['Delivered','Cancelled'].includes(s));
    if(!next.length)throw new Error('No further status updates are available to your role.');
    UI.modal('Update repair status',`<p class="info-note">Current status: ${E(t.status)}</p>${UI.select('Next status','status',next,next[0])}${UI.area('Update note','note','','maxlength="1000"')}<div id="handoverFields" hidden><p>Confirm before handing over the device:</p><div class="checklist-vertical"><label><input type="checkbox" name="tested">Device tested with the customer</label><label><input type="checkbox" name="accessories">Accessories returned</label><label><input type="checkbox" name="received">Customer received the device</label></div></div><div id="cancelInfo" class="info-note" hidden>Cancelling returns used parts to inventory. An existing unpaid invoice must be deleted first.</div>`,{submit:'Save status',onSubmit:async p=>{await Repo.setStatus(id,p.status,p.note,{tested:!!p.tested,accessories:!!p.accessories,received:!!p.received});toast('Status updated.');await App.render();},after:overlay=>{const select=overlay.querySelector('[name=status]');const update=()=>{overlay.querySelector('#handoverFields').hidden=select.value!=='Delivered';overlay.querySelector('#cancelInfo').hidden=select.value!=='Cancelled';};select.onchange=update;update();}});
  },
  async action(action,id,button) {
    if(action==='ticket-new')return this.edit();
    if(action==='ticket-edit')return this.edit(id);
    if(action==='ticket-view')return this.detail(id);
    if(action==='ticket-status')return this.status(id);
    if(action==='ticket-note')return UI.modal('Add repair note',UI.area('Repair note','note','','required maxlength="2000"'),{submit:'Save note',onSubmit:async p=>{await Repo.addNote(id,p.note);toast('Note saved.');await App.render();}});
    if(action==='ticket-usepart'){
      const parts=Storage.getAll('inventory').filter(p=>p.quantity>0);if(!parts.length)throw new Error('No parts are in stock. Add or restock inventory first.');
      return UI.modal('Use an inventory part',UI.select('Available part','part_id',parts.map(p=>[p.id,`${p.name} · ${p.quantity} in stock · ${formatCurrency(p.selling_price)}`]))+UI.field('Quantity','quantity',1,'number','min="1" step="1" required'),{submit:'Use part',onSubmit:async p=>{await Repo.usePart(id,p.part_id,p.quantity);toast('Part added and stock updated.');await App.render();}});
    }
    if(action==='ticket-returnpart')return UI.confirm('Return all units of this part to inventory?',()=>Repo.returnPart(id,button.dataset.part));
    if(action==='ticket-photo')return UI.modal('Add repair photo',UI.select('Photo type','kind',['Before','After'])+UI.field('Caption','caption','','text','maxlength="200"')+UI.field('Image (JPEG, PNG, WebP; up to 5 MB)','photo','','file','accept="image/jpeg,image/png,image/webp" required'),{submit:'Save photo',onSubmit:async(p,form)=>{await Repo.addPhoto(id,form.elements.photo.files[0],p.kind,p.caption);toast('Photo saved.');await App.render();}});
    if(action==='ticket-photo-delete')return UI.confirm('Remove this repair photo?',()=>Repo.deletePhoto(id,button.dataset.photo));
    if(action==='ticket-photo-view'){
      const t=ticketAccess(Storage.database(),id);const photo=t.photos.find(p=>p.id===button.dataset.photo);const src=await PhotoStore.get(photo?.id);if(!src)throw new Error('This photo is unavailable.');return UI.modal(photo.caption||photo.kind+' repair photo',`<img class="full-photo" src="${E(src)}" alt="${E(photo.caption||'Repair photo')}">`,{wide:true});
    }
    if(action==='ticket-export')UI.csv('repflow-tickets.csv',['Ticket','Customer','Device','Status','Priority','Technician','Due date'],(this.filtered||[]).map(t=>[t.id,App.customer(t.customer_id),t.model,t.status,t.priority,App.technician(t.technician_id),t.due_date]));
  }
};
